C*==mod_tauij.f    processed by SPAG 6.55Rc at 21:33 on 17 Mar 2008
      MODULE MOD_TAUIJ
C   ********************************************************************
C   *                                                                  *
C   *  module to store all variables connected with    TAUIJ           *
C   *                                                                  *
C   *                                                                  *
C   ********************************************************************
C
      IMPLICIT NONE
C
C*** Start of declarations rewritten by SPAG
C
C Local variables
C
      REAL*8 CLURAD_TAUIJ_CL(:),DQCLU_TAUIJ_CL(:,:),KTABTAUIJ(:,:),
     &       RQCLU_TAUIJ_CL(:,:,:),WKTABTAUIJ(:)
      INTEGER IK_IKTABTAUIJ(:),IQ_QTAB1_TAUIJ(:),IQ_TAUIJ(:),
     &        IQ_TAUIJ_CL(:,:),ISYM_IKTABTAUIJ(:),ITAUIJ_LOOP(:),
     &        ITAUJI_LOOP(:),JQTAB_TAUIJMAX,JQ_QTAB2_TAUIJ(:,:),
     &        JQ_TAUIJ(:),J_CL,N123TAUIJMAX,N5VEC_TAUIJ(:,:),
     &        N5VEC_TAUIJ_CL(:,:,:),NKTABTAUIJ,NLOOP_TAUIJ,
     &        NQCLUMAX_TAUIJ_CL,NQCLU_TAUIJ_CL(:),NQSHLCLU_TAUIJ_CL(:,:)
     &        ,NQTAB1_TAUIJ,NQTAB2_TAUIJ(:),NSHLCLUMAX_TAUIJ_CL,
     &        NSHLCLU_TAUIJ_CL(:),NSPIN,NTAUIJ,NTAUIJ_QTAB2_TAUIJ(:,:)
      LOGICAL SELECTED_TAUIJ_CL(:,:),CALC_OFF_DIAGONAL_TAUIJ_EMBEDDED
      COMPLEX*16 TAUIJ(:,:,:,:),TAUQQ_CLU(:,:,:,:)
      SAVE CLURAD_TAUIJ_CL,DQCLU_TAUIJ_CL,IK_IKTABTAUIJ,IQ_QTAB1_TAUIJ,
     &     IQ_TAUIJ,IQ_TAUIJ_CL,ISYM_IKTABTAUIJ,ITAUIJ_LOOP,ITAUJI_LOOP,
     &     JQTAB_TAUIJMAX,JQ_QTAB2_TAUIJ,JQ_TAUIJ,KTABTAUIJ,WKTABTAUIJ,
     &     N123TAUIJMAX,N5VEC_TAUIJ,N5VEC_TAUIJ_CL,NKTABTAUIJ,
     &     NQCLUMAX_TAUIJ_CL,NQCLU_TAUIJ_CL,NQSHLCLU_TAUIJ_CL,
     &     NQTAB1_TAUIJ,NQTAB2_TAUIJ,NSHLCLUMAX_TAUIJ_CL,
     &     NSHLCLU_TAUIJ_CL,NTAUIJ_QTAB2_TAUIJ,RQCLU_TAUIJ_CL,
     &     SELECTED_TAUIJ_CL,TAUIJ,CALC_OFF_DIAGONAL_TAUIJ_EMBEDDED
C
C*** End of declarations rewritten by SPAG
C
      DATA NSPIN/999999/,NLOOP_TAUIJ/999999/,NTAUIJ/999999/
      DATA CALC_OFF_DIAGONAL_TAUIJ_EMBEDDED/.FALSE./
C
      ALLOCATABLE NTAUIJ_QTAB2_TAUIJ,IQ_QTAB1_TAUIJ
      ALLOCATABLE JQ_QTAB2_TAUIJ,NQTAB2_TAUIJ,IQ_TAUIJ,JQ_TAUIJ
      ALLOCATABLE TAUIJ,N5VEC_TAUIJ,TAUQQ_CLU
      ALLOCATABLE IK_IKTABTAUIJ,ISYM_IKTABTAUIJ,KTABTAUIJ,WKTABTAUIJ
      ALLOCATABLE ITAUIJ_LOOP,ITAUJI_LOOP
      ALLOCATABLE NSHLCLU_TAUIJ_CL,CLURAD_TAUIJ_CL,NQCLU_TAUIJ_CL
      ALLOCATABLE RQCLU_TAUIJ_CL,DQCLU_TAUIJ_CL,SELECTED_TAUIJ_CL
      ALLOCATABLE IQ_TAUIJ_CL,N5VEC_TAUIJ_CL,NQSHLCLU_TAUIJ_CL
C
      END
