C*==mod_symmetry.f    processed by SPAG 6.70Rc at 17:33 on  2 Sep 2014
      MODULE MOD_SYMMETRY
C   ********************************************************************
C   *                                                                  *
C   *  module to store all tables dependent ONLY on   SYMMETRY         *
C   *                                                                  *
C   ********************************************************************
C
      IMPLICIT NONE
C
C*** Start of declarations rewritten by SPAG
C
C PARAMETER definitions
C
      INTEGER NSYMMAX
      PARAMETER (NSYMMAX=48)
C
C Local variables
C
      COMPLEX*16 DROT(:,:,:)
      INTEGER ICL_IJQCLU(:,:),IQ0_IQCLU(:),IQCLU_EQCLU(:,:),
     &        IQCLU_REP_IJQCLU(:,:),IQEQ(:,:),IQORGQP(:,:),IQPSYMQ(:,:),
     &        IQREPMSYM(:),IQREPQ(:),IQ_MBCL(:,:),ISYMGENQ(:),
     &        ISYM_GEN_IJQCLU(:,:),IWEDGEROT(NSYMMAX),
     &        JQCLU_REP_IJQCLU(:,:),NCL,NCL_IJQCLU,NCOPY_IJQCLU,
     &        NELMTMAX,NMB_CL(:),NMSYM,NQCLU_EQCLU(:),NQEQ(:),
     &        NSFTSYMQ(:,:,:),NSYM,NSYMACCEPTED,NSYMACCEPTED_CLU,
     &        NSYMCRYSYS,NVEC0_IQCLU(:,:),NWEDGE,SNTAUUVMAX,
     &        SYMDET(NSYMMAX)
      REAL*8 MROTK(3,3,NSYMMAX),MROTR(3,3,NSYMMAX),SYMEULANG(3,NSYMMAX),
     &       SYMTVEC(3,NSYMMAX),MREP_Q(:,:,:)
      LOGICAL NO_SYMMETRY,NO_SYMMETRY_CLU,NO_SYMMETRY_LINRESP,
     &        SYMACCEPTED(NSYMMAX),SYMACCEPTED_CLU(NSYMMAX),
     &        SYMCRYSYS(NSYMMAX),SYMMETRIZE_MSS,SYMMETRIZE_POT,
     &        SYMMETRIZE_RHO,SYMMETRIZE_TAU,SYMTAUTET_AVAILABLE,
     &        SYMUNITARY(NSYMMAX)
      CHARACTER*4 SYMSYMBL(NSYMMAX)
      SAVE DROT,ICL_IJQCLU,IQ0_IQCLU,IQCLU_EQCLU,IQCLU_REP_IJQCLU,IQEQ,
     &     IQORGQP,IQPSYMQ,IQREPMSYM,IQREPQ,IQ_MBCL,ISYMGENQ,
     &     ISYM_GEN_IJQCLU,IWEDGEROT,JQCLU_REP_IJQCLU,MROTK,MROTR,NCL,
     &     NCL_IJQCLU,NCOPY_IJQCLU,NMB_CL,NMSYM,NQCLU_EQCLU,NQEQ,
     &     NSFTSYMQ,NSYM,NSYMACCEPTED,NSYMACCEPTED_CLU,NSYMCRYSYS,
     &     NVEC0_IQCLU,NWEDGE,SYMACCEPTED,SYMACCEPTED_CLU,SYMCRYSYS,
     &     SYMDET,SYMEULANG,SYMSYMBL,SYMTVEC,SYMUNITARY,MREP_Q
C
C*** End of declarations rewritten by SPAG
C
      DATA NELMTMAX/1/,SNTAUUVMAX/1/
      DATA NO_SYMMETRY/.FALSE./
      DATA NO_SYMMETRY_CLU/.FALSE./
      DATA NO_SYMMETRY_LINRESP/.FALSE./
      DATA SYMMETRIZE_MSS/.TRUE./
      DATA SYMMETRIZE_TAU/.FALSE./
      DATA SYMMETRIZE_RHO/.TRUE./
      DATA SYMMETRIZE_POT/.FALSE./
      DATA SYMTAUTET_AVAILABLE/.FALSE./
C
      ALLOCATABLE DROT,MREP_Q
      ALLOCATABLE IQPSYMQ,IQREPMSYM,IQREPQ,IQORGQP,ISYMGENQ,NSFTSYMQ
      ALLOCATABLE NQCLU_EQCLU,IQCLU_EQCLU,IQEQ,NQEQ
      ALLOCATABLE NMB_CL,IQ_MBCL
C
      ALLOCATABLE IQCLU_REP_IJQCLU,JQCLU_REP_IJQCLU,ISYM_GEN_IJQCLU
      ALLOCATABLE IQ0_IQCLU,NVEC0_IQCLU,ICL_IJQCLU
C
      END
