C*==mod_rmesh.f    processed by SPAG 6.55Rc at 16:26 on 14 Jun 2007
      MODULE MOD_RMESH
C   ********************************************************************
C   *                                                                  *
C   *  module to store all rmesh information                           *
C   *                                                                  *
C   *  ALL data initialized in  <<MAINPROGRAM>>                        *
C   *                                                                  *
C   ********************************************************************
C
      IMPLICIT NONE
C*--MOD_RMESH12
      INTEGER NRMAX,NRCMAX,JRNSMIN
      PARAMETER (NRMAX=1000,NRCMAX=2*NRMAX)  ! REC changed from 750
      INTEGER NMAX_LEBGRID,N_LEBGRID,IRLAG_VORONOI_SURF_GRID(:,:)
      INTEGER NMAX_VORONOI_SURF_GRID,N_VORONOI_SURF_GRID(:)
      PARAMETER (NMAX_LEBGRID=434)
C
      REAL*8 ARMSH_ASA(:),BRMSH_ASA(:),DX_ASA(:),EXPDX_ASA(:)
      REAL*8 ARMSH_FP(:),BRMSH_FP(:),DX_FP(:),EXPDX_FP(:)
      REAL*8 ARMSH(:),BRMSH(:),DX(:),RWS(:),RMT(:)
      REAL*8 R(:,:),DRDI(:,:),R2DRDI(:,:),DRDIOVR(:,:)
      REAL*8 FLMSF(:,:,:),WINTLM(:,:,:)
      REAL*8 RHAT_LEBGRID(:,:),W_LEBGRID(:,:),Y_LEBGRID(:,:),D_LGM(:,:)
      REAL*8 RHAT_VORONOI_SURF_GRID(:,:,:),W_VORONOI_SURF_GRID(:,:)
      REAL*8 D_VORONOI_SURF_GRID(:,:),Y_VORONOI_SURF_GRID(:,:,:)
      REAL*8 W_RADINT(:,:),R2DRDI_W00(:,:),R2DRDI_W00_RADINT(:,:)
      REAL*8 DRDI_W_RADINT(:,:),R2DRDI_W_RADINT(:,:)
      REAL*8 VOL_AC(:),VOL_AC_ASA(:),VOL_AC_FP(:),VOL_IS_ASA_ANA(:),
     &       VOL_IS_ASA_NUM(:),VOL_IS_FP_NUM(:)
      REAL*8 RAUX1(:),RAUX2(:)
      REAL*8 DRDI_COR(:,:),DRDIOVR_COR(:,:),R_COR(:,:)
      REAL*8 BASSCALE(3)
      COMPLEX*16 CAUX1(:),CAUX2(:)

      CHARACTER*12 RMESHTYPE
      INTEGER JRWS_ASA(:),JRMT_ASA(:),NPAN_ASA(:),JRCUT_ASA(:,:)
      INTEGER JRWS_FP(:),JRMT_FP(:),NPAN_FP(:),JRCUT_FP(:,:)
      INTEGER JRWS(:),JRMT(:),JRCRI(:),JRNS1(:),NPAN(:),NRNS(:),
     &        NRSFTOT(:),NSF(:),JRCUT(:,:),LMISF(:,:),KLMSF(:,:),
     &        ISFLM(:,:),NM,NMMAX,NSFMAX,NPANMAX,
     &        NRSFMAX,NMCLU,NMHOST,NLSFMAX,NLMSFMAX,NLSF,NLMSF
      INTEGER JRCUT_SAV(:,:),NPAN_SAV(:)
      
      LOGICAL SPHERCELL,FULLPOT,FINITE_NUCLEUS,CARTESIAN
C
C---------------------------------------- variables depending only on NM
C
      ALLOCATABLE JRCRI,JRMT,JRNS1,JRWS,NPAN,NRNS,NRSFTOT,NSF
      ALLOCATABLE ARMSH,BRMSH,DX,RWS,RMT
      ALLOCATABLE VOL_IS_ASA_NUM,VOL_IS_ASA_ANA,VOL_IS_FP_NUM
      ALLOCATABLE VOL_AC,VOL_AC_ASA,VOL_AC_FP
      ALLOCATABLE JRCUT_SAV,NPAN_SAV      
      ALLOCATABLE ARMSH_ASA,BRMSH_ASA,DX_ASA,EXPDX_ASA
      ALLOCATABLE ARMSH_FP,BRMSH_FP,DX_FP,EXPDX_FP
      ALLOCATABLE JRWS_ASA,JRMT_ASA,NPAN_ASA,JRCUT_ASA
      ALLOCATABLE JRWS_FP,JRMT_FP,NPAN_FP,JRCUT_FP
C
C--------------------------------------------- variables depending on NR
C
      ALLOCATABLE RAUX1,RAUX2,CAUX1,CAUX2
C
C-------------------------------------- variables depending on NM and NR
C
      ALLOCATABLE R,DRDI,R2DRDI,DRDIOVR
      ALLOCATABLE R_COR,DRDI_COR,DRDIOVR_COR
      ALLOCATABLE W_RADINT,DRDI_W_RADINT,R2DRDI_W_RADINT
      ALLOCATABLE R2DRDI_W00,R2DRDI_W00_RADINT
C
C-------------------------------------- variables depending on NM and SF
C
      ALLOCATABLE FLMSF,ISFLM,JRCUT,KLMSF,LMISF,WINTLM
C
C--------------------------------- variables connected with Lebedev grid
C
      ALLOCATABLE D_LGM,RHAT_LEBGRID,W_LEBGRID,Y_LEBGRID
C
C------------------------- variables connected with Voronoi surface grid
C
      ALLOCATABLE RHAT_VORONOI_SURF_GRID,W_VORONOI_SURF_GRID
      ALLOCATABLE D_VORONOI_SURF_GRID,N_VORONOI_SURF_GRID
      ALLOCATABLE Y_VORONOI_SURF_GRID,IRLAG_VORONOI_SURF_GRID
C
      DATA JRNSMIN/1/,SPHERCELL/.FALSE./,FINITE_NUCLEUS/.FALSE./
      DATA NRSFMAX/1/,NPANMAX/1/,NSFMAX/1/,NMCLU/999999/
      DATA NLSFMAX/0/,NLMSFMAX/0/,NLSF/0/,NLMSF/0/
      DATA BASSCALE/1D0,1D0,1D0/,CARTESIAN/.TRUE./
C     
      SAVE JRCRI,JRMT,JRNS1,JRWS,NPAN,NRNS,NRSFTOT,NSF,ARMSH,BRMSH,DX,
     &   RWS,RMT,R,DRDI,R2DRDI,DRDIOVR,
     &   W_RADINT,DRDI_W_RADINT,R2DRDI_W_RADINT,
     &   R2DRDI_W00,R2DRDI_W00_RADINT,
     &   FLMSF,ISFLM,JRCUT,KLMSF,LMISF,WINTLM,
     &   NM,NMMAX,NSFMAX,NPANMAX,NRSFMAX,RMESHTYPE,FINITE_NUCLEUS,
     &   FULLPOT,NMCLU,NMHOST,NLSFMAX,NLMSFMAX,NLSF,NLMSF,
     &   D_LGM,RHAT_LEBGRID,N_LEBGRID,W_LEBGRID,Y_LEBGRID
      SAVE VOL_IS_ASA_NUM,VOL_IS_ASA_ANA,VOL_IS_FP_NUM,
     &     VOL_AC,VOL_AC_ASA,VOL_AC_FP
      SAVE RAUX1,RAUX2,CAUX1,CAUX2
      SAVE JRCUT_SAV,NPAN_SAV
      SAVE ARMSH_ASA,BRMSH_ASA,DX_ASA,EXPDX_ASA
      SAVE ARMSH_FP,BRMSH_FP,DX_FP,EXPDX_FP
      SAVE JRWS_ASA,JRMT_ASA,NPAN_ASA,JRCUT_ASA
      SAVE JRWS_FP,JRMT_FP,NPAN_FP,JRCUT_FP
      SAVE R_COR,DRDI_COR,DRDIOVR_COR
      SAVE CARTESIAN,BASSCALE
      SAVE NMAX_VORONOI_SURF_GRID,N_VORONOI_SURF_GRID
      SAVE RHAT_VORONOI_SURF_GRID,W_VORONOI_SURF_GRID
      SAVE D_VORONOI_SURF_GRID,Y_VORONOI_SURF_GRID
      SAVE IRLAG_VORONOI_SURF_GRID
C     
      END
